# Generated by Django 2.2.13 on 2020-06-18 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0002_auto_20200611_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertise.City')),
            ],
        ),
        migrations.CreateModel(
            name='NeighborHood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertise.Town')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertiseAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_detail', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='advertise.Advertise')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertise.City')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertise.NeighborHood')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertise.Town')),
            ],
        ),
    ]
